title: TradingLaboratory Wiki
description: База знаний об индикаторах и стратегиях
theme: just-the-docs

# URL settings
url: "https://tradinglaboratory.github.io"
baseurl: /wiki

# Color scheme
color_scheme: default

# Enable search
search_enabled: true

# Enable headings anchors
heading_anchors: true

# Footer "Built with Jekyll" link
footer_content: "© 2026 TradingLaboratory"

# Aux links (показываются внизу боковой панели)
aux_links:
  GitHub: https://github.com/TradingLaboratory/wiki
