site_name: TradingLaboratory Wiki
site_url: https://tradinglaboratory.github.io/wiki/
theme:
  name: material
  palette:
    primary: indigo
    scheme: default
  features:
    # - navigation.tabs    # ← это показывает вкладки сверху
    - search.suggest
    - content.code.copy

nav:  
  - Главная: index.md
  # ← можно делать вложенные разделы (используем не табулятор, а 2 пробела)
  - Начало работы: getting-started.md
    - API Documentation: api.md
    - Examples: examples.md
  - Решение проблем: troubleshooting.md

markdown_extensions:
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: true
  - tables
  - admonition